spring:
  thymeleaf:
    cache: true

nest:
  # bsc
  chainId: 56
  # BSC NEST
  nestTokenAddress: "0x98f8669f6481ebb341b522fcd3663f79a3d1a6a7"
  # quote mining contract address
  nestMiningAddress: "0x09CE0e021195BA2c1CDE62A8B187abf810951540"
  miningFeeRateInflateFactor: 10000

